### ISSUE TITLE
Support .NET Core

### ISSUE THREAD

**Issue by AsValeO** [notanaverageman/Bindables#17]
Please, add a .NET Core support

**Comment by notanaverageman** [comment]
Last time I tried supporting both .NET Framework and .NET Core, I had issues with Fody tooling. I may take a look at it again next week.

However, in the long run I am considering switching to Roslyn code generation instead of IL weaving with Fody. It can handle both frameworks easily and it does not break compatibility as Fody does. And I don't like the "mandatory donation" thing with Fody. They break compatibility, do not document it and ask money to raise an issue about it.

**Comment by notanaverageman** [comment]
Should be resolved with 6.0.0. Still using Fody by the way.
