### ISSUE TITLE
Unable to build with dotnet 5.0 CLI

### ISSUE THREAD

**Issue by timonsdad** [notanaverageman/Bindables#21]
We're trying to upgrade our build to use the dotnet 5.0 CLI, but our project that includes Bindables fails to build with this error.

```
Fody: An unhandled exception occurred:
Exception:
Could not find file 'C:\Users\username\.nuget\packages\bindables.fody\6.0.0\Bindables.Fody.dll'.
Type:
System.IO.FileNotFoundException
StackTrace:
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.OpenRead(String path)
   at IsolatedAssemblyLoadContext.LoadNotLocked(String assemblyPath) in C:\projects\fody\FodyCommon\IsolatedAssemblyLoadContext.cs:line 67
   at InnerWeaver.LoadFromFile(String assemblyPath) in C:\projects\fody\FodyIsolated\AssemblyLoader.cs:line 24
   at InnerWeaver.LoadWeaverAssembly(String assemblyPath) in C:\projects\fody\FodyIsolated\AssemblyLoader.cs:line 18
   at InnerWeaver.InitialiseWeaver(WeaverEntry weaverConfig) in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 157
   at InnerWeaver.InitialiseWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 145
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 106
Source:
System.Private.CoreLib
TargetSite:
Microsoft.Win32.SafeHandles.SafeFileHandle ValidateFileHandle(Microsoft.Win32.SafeHandles.SafeFileHandle)
```

Other weavers appear to be working fine.

**Comment by notanaverageman** [comment]
I have looked at the issue, but it seems that Fody only works for .NET Standard projects and this project cannot target .NET Standard since WPF does not support it. I have managed to workaround this in the past, but I have no intention to spend time on this again. I myself haven't use this package or Fody for years and I don't think I will ever again.

If you can manage to convince Fody maintainers to add support for non .NET Standard projects, I can update the project accordingly. Or if anyone is willing to fix the targets files, I can accept a PR too. However, I will not spend my time on this.

**Comment by FreeApophis** [comment]
I ran into the same Problem, it compiles in Visual Studio but not with 'dotnet build'.

Other Fody plugins do not have this problem in the same project, I did not find any restriction on Fody target framework, I doubt that this is the reason: the problem is, at that place is no .dll, the dll is located:

`.nuget\packages\bindables.fody\6.0.0\lib\<platform>\Bindables.Fody.dll`
not in `.nuget\packages\bindables.fody\6.0.0\Bindables.Fody.dll`

Please at least inform Fody, that this plugin is no loger maintained, it is still listed on Fody as a maintained plugin:

https://github.com/Fody/Home/blob/master/pages/addins.md

**Comment by notanaverageman** [comment]
I created a [pull request](https://github.com/Fody/Home/pull/324) to remove this addin from that list.

The problem is that Fody assumes the projects targets either .NET Framework or .NET Standard or both. WPF libraries are not allowed to target .NET Standard. I have copied .targets and .props files from Fody in the past and it seems that the way that Fody expects the NuGet package structure has changed. So these .targets and .props files should be somehow updated unless Fody supports this library's case and then they can be removed completely.

As I said earlier, I don't intend to spend time on this and I will probably archive the project.

Related files:

- [FodyPackaging.props](https://github.com/notanaverageman/Bindables/blob/896b2f3466b6f7db7240affd3384726da9d8b21e/Bindables/FodyPackaging.props)
- [FodyPackaging.targets](https://github.com/notanaverageman/Bindables/blob/896b2f3466b6f7db7240affd3384726da9d8b21e/Bindables/FodyPackaging.targets)
- [Weaver.props](https://github.com/notanaverageman/Bindables/blob/896b2f3466b6f7db7240affd3384726da9d8b21e/Bindables/Weaver.props)

**Comment by Int32Overflow** [comment]
@notanaverageman You wrote that you no longer use Fody. Do you use another tool in the meantime? How do you write DependencyProperties?

**Comment by notanaverageman** [comment]
Until a few months ago I was writing them manually. Recently I have rewritten the project as a Roslyn source generator, but haven't found the time to update the documentation.

New version is available as a [NuGet package](https://www.nuget.org/packages/Bindables.Wpf), but for now you have to look at the test cases to learn how to use it.

**Comment by notanaverageman** [comment]
I have updated the documentation.
