### ISSUE TITLE
Error Build with generic.xaml and CustomControl

### ISSUE THREAD

**Issue by AshIceLoky** [notanaverageman/Bindables#9]
I try to your [DependancyProperty] to create a simple ImageButton

`    public class ButtonImage : Button
    {
        static ButtonImage()
        {
            DefaultStyleKeyProperty.OverrideMetadata(typeof(ButtonImage), new FrameworkPropertyMetadata(typeof(ButtonImage)));
        }
        [DependencyProperty] public ImageSource ImageA{ get; set; }
    }`

`    <Style TargetType="{x:Type controls:ButtonImage}">
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="{x:Type controls:ButtonImage}">
                    <Grid VerticalAlignment="Center" Margin="5">
                        <Grid.RowDefinitions>
                            <RowDefinition Height="45"/>
                            <RowDefinition Height="25"/>
                        </Grid.RowDefinitions>
                            <Image Grid.Row="0"  Source="{TemplateBinding ImageA}"  />
                        <Label Grid.Row="1" Content="{TemplateBinding Content}"  />
                    </Grid>
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>`

But build fail, No found ImageA in the class ButtonImage 
<Image Grid.Row="0"  Source="{TemplateBinding ImageA}"  />

With a standard full definition of DependencyProperty , its OK

**Comment by notanaverageman** [comment]
`TemplateBinding ` works at compile time and requires the static `DependencyProperty` property to be found. Since that property is generated after the compilation there will not be a way to satisfy `TemplateBinding`.

However, there is a simple fix: Instead of `TemplateBinding` use a regular `Binding` with a `RelativeSource` to `TemplatedParent`. Here is an example:

`<Image Grid.Row="0" Source="{Binding ImageA, RelativeSource={RelativeSource TemplatedParent}}" />`
